### ISSUE TITLE
enable GDB debugging

### ISSUE THREAD

**Issue by yhuanghamu** [gpgpu-sim/ispass2009-benchmarks#3]
if pepole want to experience gdb with these benchmarks.  Besides enbale debugger mode in gpgpu-sim, by using 
source setup_environment debug

They should also edit the makefile of the benchmark of interest by replacing
CFLAGS  :=   -O3
with
CFLAGS := -g

Both gpgpu-sim and benchmarks should have debug symbols.
I believe that you should mention this in your reademe

**Comment by smadenur** [comment]
What's the command used to debug using gdb?
I tried gdb --args `cat README.GPGPU-sim`, but still gdb can't find debugging symbols. Can you help with the command?
